# Generated by Django 3.0.3 on 2020-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200401_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='150x150px', upload_to='images/blog/%Y/%m/%d', verbose_name='/home/root1/locallibrary/catalog/images/local_library_model_uml.png')),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
