# Generated by Django 3.0.3 on 2020-04-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200406_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
