# Generated by Django 3.0.3 on 2020-04-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='case_preview',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='media/local_library_model_uml.png', verbose_name='Ссылка картинки'),
        ),
    ]
